### ISSUE TITLE
Newtonsoft.Json.JsonReaderException

### ISSUE THREAD

**Issue by Pentadome** [testcontainers/testcontainers-dotnet#672]
**Describe the bug**
```csharp
var dbContainer = new TestcontainersBuilder<MsSqlTestcontainer>()
    .WithDatabase(
        new MsSqlTestcontainerConfiguration("mcr.microsoft.com:2022-latest")
        {
            Password = Guid.NewGuid().ToString(),
        }
    )
    .Build();
    
await dbContainer.StartAsync(); ///< -- Newtonsoft.Json.JsonReaderException : Error parsing undefined value. Path '', line 1, position 2.
```

```
Newtonsoft.Json.JsonReaderException
  HResult=0x80131500
  Message=Error parsing undefined value. Path '', line 1, position 2.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.JsonTextReader.<MatchAndSetAsync>d__21.MoveNext()
   at Newtonsoft.Json.JsonTextReader.<ParseValueAsync>d__8.MoveNext()
   at Docker.DotNet.Models.StreamUtil.<MonitorStreamForMessagesAsync>d__1`1.MoveNext()
   at Docker.DotNet.Models.StreamUtil.<MonitorResponseForMessagesAsync>d__2`1.MoveNext()
   at DotNet.Testcontainers.Clients.DockerImageOperations.<CreateAsync>d__9.MoveNext() in /home/runner/work/testcontainers-dotnet/testcontainers-dotnet/src/Testcontainers/Clients/DockerImageOperations.cs:line 81
   at DotNet.Testcontainers.Clients.TestcontainersClient.<RunAsync>d__22.MoveNext() in /home/runner/work/testcontainers-dotnet/testcontainers-dotnet/src/Testcontainers/Clients/TestcontainersClient.cs:line 252
   at DotNet.Testcontainers.Containers.TestcontainersContainer.<Create>d__34.MoveNext() in /home/runner/work/testcontainers-dotnet/testcontainers-dotnet/src/Testcontainers/Containers/TestcontainersContainer.cs:line 283
   at DotNet.Testcontainers.Containers.TestcontainersContainer.<StartAsync>d__27.MoveNext() in /home/runner/work/testcontainers-dotnet/testcontainers-dotnet/src/Testcontainers/Containers/TestcontainersContainer.cs:line 179
```

**Desktop (please complete the following information):**
```
OS Name	Microsoft Windows 10 Pro	
Version	10.0.19044 Build 19044	
```

**Additional context**
Sorry if it is something obvious, I really don't understand why I get this Json error.

**Comment by HofmeisterAn** [comment]
Do you use the latest version? Might be https://github.com/testcontainers/testcontainers-dotnet/issues/634#issuecomment-1288667375 and fixed with 2.2.0.

**Comment by Pentadome** [comment]
Yes i'm using `2.2.0`.

**Comment by HofmeisterAn** [comment]
The image looks not correct `mcr.microsoft.com:2022-latest`.

**Comment by Pentadome** [comment]
> The image looks not correct `mcr.microsoft.com:2022-latest`.

Ohh.. I feel like a idiot haha. It still doesnt work when i am logged in in docker dekstop, but i saw that was a known issue: 

![image](https://user-images.githubusercontent.com/16758470/201375701-7a9d7a81-a42f-4f26-9f1c-24198a5ac5bc.png)

But I got it working now.
You dont want to know how much time i wasted 🤦

Thanks <3

**Comment by HofmeisterAn** [comment]
> Ohh.. I feel like a idiot haha.

No worries. Happens to all of us sometimes.

> It still doesnt work when i am logged in in docker dekstop, but i saw that was a known issue

Yes, we will take care of it in the next days.
